server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://hadoop001:3306/metrics
    username: ruoze
    password: ruozedata
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

